// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwbnjmnjvywueqacmugf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3Ym5qbW5qdnl3dWVxYWNtdWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NTU1NzQsImV4cCI6MjA1OTAzMTU3NH0.aq1xCSq4gcOcxuJUdQk3vt2W8HcIxU2wQD_s0LsATSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);